---
title: "Untitled"
author: "zhuoran zhang"
date: "2020/9/5"
output: html_document
---

```{r}
adni <- read.csv(file="C:/Users/ucizz/Onedrive/Desktop/research/paper 2/paper 2 reference/ADNI1_Final_Clean.csv")
brain <- read.csv(file="C:/Users/ucizz/Onedrive/Desktop/research/paper 2/paper 2 reference/adniJointLabelFusionMeasurements.csv")

adni_id <- read.csv(file="C:/Users/ucizz/OneDrive/Desktop/research/paper 2/ADNI_ID_updated_090120.csv")

adni_sub <- adni[adni$IMAGE_ID %in% brain$Image.ID,]
adni_sub <- adni_sub[order(adni_sub$IMAGE_ID),]
brain <- brain[order(brain$Image.ID),]

merged <- cbind(adni_sub,brain[,3:dim(brain)[2]])
merged <- merged[order(merged$RID),]


baseline <- merged[merged$VISIT=="sc",]


### Clean data

baseline=baseline[,c(3,6,7:13,18:27,41:50)]
baseline=na.omit(baseline)

### Extract edu year
adni_id_sub <- adni_id[adni_id$RID %in% baseline$RID,]
adni_id_sub <- adni_id_sub[order(adni_id_sub$RID),]
adni_id_sub <- na.omit(adni_id_sub)
edu_year <- unlist(lapply(split(adni_id_sub$PTEDUCAT,adni_id_sub$RID),unique))

baseline <- baseline[order(baseline$RID),]


baseline$GENDER= (baseline$GENDER=="M")*1
baseline$edu <- edu_year
baseline$MCI <- (baseline$DIAGNOSIS=="MCI")*1
baseline$AD <- (baseline$DIAGNOSIS=="AD")*1

baseline <- baseline[,-4]

baseline[baseline$edu<12,]$edu <- 1
baseline[baseline$edu==12,]$edu <- 2
baseline[(baseline$edu>12) & (baseline$edu<16),]$edu <- 3
baseline[baseline$edu>=16,]$edu <- 4

baseline[,c(9:17,19:28)] <- scale(baseline[,c(9:17,19:28)])
```

```{r}
nhanes_rep = read.csv("C:/Users/ucizz/Onedrive/Desktop/research/paper 2/paper 2 reference/nhanes_rep.csv")
###education level defined as : edu year <12, 12<edu year <16 and >16
nhanes_rep <- nhanes_rep[,2:4]

adni_base <- baseline



adni_base$edu <- factor(adni_base$edu, 
                        levels=c(1,2,3,4), 
                        labels=c("less than 12","high school/GED","some college","college grad or higher"))
adni_base$GENDER <- 1-adni_base$GENDER

adni_base <- adni_base[,c(2,3,29)]
adni_base$bias <- 1
nhanes_rep$bias <-0
names(adni_base) <- c("age","female","edu","bias")
com <- rbind(adni_base,nhanes_rep)
```



```{r}
weight_ridge <- function(data,weights,sigma2){
### OLS estimate alpha
  x <- data[,c(2:17,19:31)]
  X_mat <- as.matrix( cbind(rep(1,dim(x)[1]),x) )
  y <- data[,18]
  W <- diag(as.vector(weights))
  
    W <- diag(weights)
  P <- eigen(t(X_mat)%*%W%*%X_mat)$vectors #### P eigenvectors  t(P) in latex document= P here
  X <- X_mat%*%(P)
  alpha_hat <- solve(t(X)%*%W%*%X/nrow(X))%*%t(X)%*%W%*%y/nrow(X)
  delta= eigen(t(X_mat)%*%W%*%X_mat)$values*alpha_hat^2/sigma2
  K <- nrow(x)*diag( as.vector( rep(sigma2,dim(alpha_hat)[1])/alpha_hat^2))*diag(t(X)%*%W^2%*%X)/diag(t(X)%*%W%*%X) 
  alpha_history <-c((P)%*%alpha_hat)
  alpha_temp <-c()
  i=0
  while( sum(abs(alpha_hat-alpha_temp)<rep(0.005,length(alpha_hat)))<length(alpha_hat) ){
    
    K <- 1/nrow(x)*diag( as.vector( rep(sigma2,dim(alpha_hat)[1])/alpha_hat^2)*diag(t(X)%*%W^2%*%X)/diag(t(X)%*%W%*%X)  )
    if(sum(abs(alpha_hat)<1e-5)>0 ){
      alpha_hat[abs(alpha_hat)<1e-5] <-0
      K[abs(alpha_hat)<1e-5,abs(alpha_hat)<1e-5]<-Inf
    }
    alpha_temp <- alpha_hat
    alpha_hat <- diag( 1/(diag(t(X)%*%W%*%X/nrow(X) +K)) )%*%t(X)%*%W%*%y/nrow(X)

    ##print(alpha_hat)
    ##print(K)
    
    alpha_history <- cbind(alpha_history,(P)%*%alpha_hat)
      i=i+1
  ##print(i)
  }
  return(list(beta=(P)%*%alpha_hat, K=K) )

  ##return(alpha_history)
}




weight_ridge0 <- function(data,sigma2){
### OLS estimate alpha
   x <- data[,c(2:17,19:31)]
  X_mat <- as.matrix( cbind(rep(1,dim(x)[1]),x) )
  y <- data[,18]
  P <- eigen(t(X_mat)%*%X_mat)$vectors #### P eigenvectors  t(P) in latex document= P here
  X <- X_mat%*%(P)
  alpha_hat <- solve(t(X)%*%X)%*%t(X)%*%y
  delta= eigen(t(X_mat)%*%X_mat)$values*alpha_hat^2/sigma2
  K <- nrow(X)*diag( as.vector( rep(sigma2,dim(alpha_hat)[1])/alpha_hat^2)) 
  alpha_history <-c((P)%*%alpha_hat)
  alpha_temp <-c()
  i=0
  while( sum(abs(alpha_hat-alpha_temp)<rep(0.005,length(alpha_hat)))<length(alpha_hat) ){
    
    K <- 1/nrow(x)*diag( as.vector( rep(sigma2,dim(alpha_hat)[1])/alpha_hat^2))
    if(sum(abs(alpha_hat)<1e-5)>0 ){
      alpha_hat[abs(alpha_hat)<1e-5] <-0
      K[abs(alpha_hat)<1e-5,abs(alpha_hat)<1e-5]<-Inf
    }
    alpha_temp <- alpha_hat
    alpha_hat <- diag( (1/(diag(t(X)%*%X/nrow(X) +K))) )%*%t(X)%*%y/nrow(X)

    ##print(alpha_hat)
    ##print(K)
    
    alpha_history <- cbind(alpha_history,(P)%*%alpha_hat)
      i=i+1
  ##print(i)
  }
  return((P)%*%alpha_hat)

  ##return(alpha_history)
}

inf.fun <- function(fit) {
  
  dm <- model.matrix(fit)
  Ihat <- (t(dm) %*% (dm * fit$fitted.values * (1 - fit$fitted.values))) / nrow(dm)
  ## influence function
  residual_weight <- resid(fit, type = "response")
  ratio <- 36188/509
  residual_weight[1:509] <- residual_weight[1:509]/ratio
  infl <- (dm * residual_weight) %*% solve(Ihat)
  return(infl)
}


IF_GWRR <- function(i, dm, y, beta, W,K, fit_log, inf_log){
  
  ########## Influence function of the ith observation
  #Ihat <- t(dm)%*%W%*%dm/nrow(dm) + K/nrow(dm)
  Ihat <- t(dm)%*%W%*%dm/nrow(dm) + K
  res <-  dm%*%beta-y
  
  term1 <- as.numeric((y[i]-dm[i,]%*%beta)*W[i,i])*as.matrix(dm[i,])
  term2_W_beta <- diag(1,nrow(dm))
  term2_beta_ep <- inf_log[i,]
  for(j in 1: nrow(dm)){

    term2_W_beta[j,j] <- -W[j,j]*t(model.matrix(fit_log)[j,]) %*% term2_beta_ep
  }
  term3_bias <- res
  ################ Newly added
  return(solve(Ihat)%*%(term1 + t(dm)%*%W%*%res/nrow(dm) - t(dm)%*%term2_W_beta%*%res/nrow(dm) )  )
}
```






```{r}
library(ggplot2)
df <- data.frame(adni_weights*10^3)
names(df) <- c("adni_weights")
ggplot(df, aes(x=adni_weights)) + 
 geom_histogram(aes(y=..density..), colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666")+theme(plot.title = element_text(hjust=0.5))+xlim(0,10)+xlab(element_blank())
```




```{r}
################ Influence function CI
## examples for predictions




averaged_covariate <- apply(baseline[,c(2:17,19:31)],2,mean)
averaged_covariate[c(4:7,28:29)] <- c(3,3,1,0,0,0)
averaged_covariate <- c(1,averaged_covariate)

wpre1=wpre2=wpre3=wpre4=wpre5=wpre6=0
pre1=pre2=pre3=pre4=pre5=pre6=0
################ Weights
model_p <- glm(bias~. , data=com,family="binomial")
est_p <- fitted(model_p,type="response")
ht_weight <- (1-est_p)/est_p
#ht_weight <- ht_weight/sum(ht_weight)

adni_weights <- ht_weight[1:dim(adni_base)[1]]
adni_weights <- adni_weights/sum(adni_weights)

lm0 <- lm(MMSCORE~.,weights=adni_weights,data=baseline[,c(2:31)])
sigma <- sum( residuals(lm0)^2  )/(dim(baseline)[1]-dim(baseline)[2])

N = dim(baseline)[1]

pre_weighted <- weight_ridge(baseline,adni_weights,sigma)$beta
pre_unweighted <- weight_ridge0(baseline,sigma)
K <- weight_ridge(baseline,adni_weights,sigma)$K
K=diag(diag(K))
diag(K)[diag(K) == Inf]=1e3 
 
x <- baseline[,c(2:17,19:31)]
dm <- as.matrix( cbind(rep(1,dim(x)[1]),x) )
#################### Influence function

#inf_log <- influence(model_p)$coefficients
inf_log <- inf.fun(model_p)
  
var_IF_GWRR <- matrix(0,(dim(dm)[2]),(dim(dm)[2]))

for(n_row in 1: nrow(dm)){
  
 if_gwrr <- IF_GWRR(n_row, dm=dm,
        y=baseline[,18],
        beta= pre_weighted,
        W = diag(adni_weights),
        K = K,
        fit_log = model_p,
        inf_log <- inf_log)
 var_IF_GWRR <- var_IF_GWRR + if_gwrr%*%t(if_gwrr)
}
var_IF_GWRR = var_IF_GWRR/nrow(dm)^2
### 1 youngest
obs1 <- averaged_covariate
obs1[c(2:3,28)] <- c(55,1,1)
wpre1 <- t(obs1)%*%pre_weighted
pre1 <- t(obs1)%*%pre_unweighted
var_wpre1 <- t(obs1)%*%(var_IF_GWRR)%*%obs1
#abs(wpre1-pre1)
### 2 oldest
obs2 <- averaged_covariate
obs2[c(2:3,28)] <- c(65,1,1)
wpre2 <- t(obs2)%*%pre_weighted
pre2 <- t(obs2)%*%pre_unweighted
var_wpre2 <- t(obs2)%*%(var_IF_GWRR)%*%obs2
#abs(wpre2-pre2)
### Less educated
obs3 <- averaged_covariate
obs3[c(2:3,28)] <- c(75,1,1)
wpre3 <- t(obs3)%*%pre_weighted
pre3 <- t(obs3)%*%pre_unweighted
var_wpre3 <- t(obs3)%*%(var_IF_GWRR)%*%obs3
#abs(wpre3-pre3)
### female
obs4 <- averaged_covariate
obs4[c(2:3,28)] <- c(65,0,4)
pre4 <- t(obs4)%*%pre_unweighted
wpre4 <- t(obs4)%*%pre_weighted
var_wpre4 <- t(obs4)%*%(var_IF_GWRR)%*%obs4
#abs(wpre4-pre4)
### male
obs5 <- averaged_covariate
obs5[c(2:3,28)] <- c(65,0,1)
wpre5 <- t(obs5)%*%pre_weighted
pre5 <- t(obs5)%*%pre_unweighted
var_wpre5 <- t(obs5)%*%(var_IF_GWRR)%*%obs5


### AD 
obs6 <- averaged_covariate
obs6[c(2:3,28,30)] <- c(65,1,1,1)
wpre6 <- t(obs6)%*%pre_weighted
pre6 <- t(obs6)%*%pre_unweighted
var_wpre6 <- t(obs6)%*%(var_IF_GWRR)%*%obs6



mean_unweight = cbind( mean(pre1), mean(pre2), mean(pre3), mean(pre4), mean(pre5), mean(pre6) )
std_unweight = cbind( sqrt(var(pre1)), sqrt(var(pre2)), sqrt(var(pre3)), sqrt(var(pre4)), sqrt(var(pre5)), sqrt(var(pre6)) )

mean_weight = cbind( mean(wpre1), mean(wpre2), mean(wpre3), mean(wpre4), mean(wpre5), mean(wpre6) )
std_weight = cbind( sqrt(var_wpre1), sqrt(var_wpre2), sqrt(var_wpre3), sqrt(var_wpre4), sqrt(var_wpre5), sqrt(var_wpre6) )

unweight_upper = mean_unweight+1.96*std_unweight
unweight_lower = mean_unweight-1.96*std_unweight

weight_upper = mean_weight+1.96*std_weight
weight_lower = mean_weight-1.96*std_weight

wpre <- cbind(wpre1,wpre2,wpre3,wpre4,wpre5,wpre6)
pre <- cbind(pre1,pre2,pre3,pre4,pre5,pre6)

result = as.data.frame( t( rbind(pre,wpre,weight_lower,weight_upper,unweight_lower,unweight_upper) ) )
names(result) = c("pre","wpre", "weight_low", "weight_up", "unweight_low", "unweight_up"  )

result
```

```{r}
####################### Bootstrap #####################
## examples for predictions
B=1000

baseline[,9:13] <- baseline[,9:13]/1000

averaged_covariate <- apply(baseline[,c(2:17,19:31)],2,mean)
averaged_covariate[c(4:7,28:29)] <- c(3,3,1,0,0,0)
averaged_covariate <- c(1,averaged_covariate)

pre1=pre2=pre3=pre4=pre5=pre6=rep(0,B)
wpre1=wpre2=wpre3=wpre4=wpre5=wpre6=rep(0,B)








lm0 <- lm(MMSCORE~.,weights=adni_weights,data=baseline[,c(2:31)])
sigma <- sum( residuals(lm0)^2  )/(dim(baseline)[1]-dim(baseline)[2])

N = dim(baseline)[1]


for(i in 1: B){
boot = sample(N,N,replace = TRUE)
adni_base_boot <- adni_base[boot,]
com_boot <- rbind(adni_base_boot,nhanes_rep)
model_p <- glm(bias~. , data=com_boot,family="binomial")
est_p <- fitted(model_p,type="response")
ht_weight <- (1-est_p)/est_p
ht_weight <- ht_weight/sum(ht_weight)

adni_weights <- ht_weight[1:dim(adni_base_boot)[1]]

baseline_boot <- baseline[boot,]





pre_weighted <- weight_ridge(baseline_boot,adni_weights,sigma)
pre_unweighted <- weight_ridge0(baseline_boot,sigma)

### 1 youngest
obs1 <- averaged_covariate
obs1[c(2:3,28)] <- c(55,0,4)
wpre1[i] <- t(obs1)%*%pre_weighted
pre1[i] <- t(obs1)%*%pre_unweighted
#abs(wpre1-pre1)
### 2 oldest
obs2 <- averaged_covariate
obs2[c(2:3,28)] <- c(89,0,4)
wpre2[i] <- t(obs2)%*%pre_weighted
pre2[i] <- t(obs2)%*%pre_unweighted
#abs(wpre2-pre2)
### Less educated
obs3 <- averaged_covariate
obs3[c(2:3,28)] <- c(75,1,1)
wpre3[i] <- t(obs3)%*%pre_weighted
pre3[i] <- t(obs3)%*%pre_unweighted
#abs(wpre3-pre3)
### female
obs4 <- averaged_covariate
obs4[c(2:3,28)] <- c(75,0,3)
wpre4[i] <- t(obs4)%*%pre_weighted
pre4[i] <- t(obs4)%*%pre_unweighted
#abs(wpre4-pre4)
### male
obs5 <- averaged_covariate
obs5[c(2:3,28)] <- c(75,1,3)
wpre5[i] <- t(obs5)%*%pre_weighted
pre5[i] <- t(obs5)%*%pre_unweighted
abs(wpre5-pre5)
### AD 
obs6 <- averaged_covariate
obs6[c(2:3,28,30)] <- c(75,1,3,1)
wpre6[i] <- t(obs6)%*%pre_weighted
pre6[i] <- t(obs6)%*%pre_unweighted
abs(wpre6-pre6)

if( round(i/100)*100 == i ){
print(i)
}

}
mean_unweight = cbind( mean(pre1), mean(pre2), mean(pre3), mean(pre4), mean(pre5), mean(pre6) )
std_unweight = cbind( sqrt(var(pre1)), sqrt(var(pre2)), sqrt(var(pre3)), sqrt(var(pre4)), sqrt(var(pre5)), sqrt(var(pre6)) )

mean_weight = cbind( mean(wpre1), mean(wpre2), mean(wpre3), mean(wpre4), mean(wpre5), mean(wpre6) )
std_weight = cbind( sqrt(var(wpre1)), sqrt(var(wpre2)), sqrt(var(wpre3)), sqrt(var(wpre4)), sqrt(var(wpre5)), sqrt(var(wpre6)) )

unweight_upper = mean_unweight+1.96*std_unweight
unweight_lower = mean_unweight-1.96*std_unweight

weight_upper = mean_weight+1.96*std_weight
weight_lower = mean_weight-1.96*std_weight

result = as.data.frame( t( rbind(weight_lower,weight_upper,unweight_lower,unweight_upper) ) )
names(result) = c("weight_low", "weight_up", "unweight_low", "unweight_up"  )
result
```

```{r}
wpre <- as.matrix( cbind(rep(1,dim(baseline)[1]),baseline[,c(2:17,19:31)]) )%*%pre_weighted
pre <- as.matrix( cbind(rep(1,dim(baseline)[1]),baseline[,c(2:17,19:31)]) )%*%pre_unweighted

max <- max(abs(wpre-pre))
max
index_max <- which(abs(wpre-pre)==max)
obmax <- as.matrix(unlist(c(1,baseline[index_max,c(2:17,19:31)])))

wpre[index_max]
pre[index_max]

```

